openfun/marion

.circleci/config.yml
src/howard/setup.cfg
src/marion/setup.cfg

This repository contains sources for linked but distinct packages that needs to be distributed separately.
We now build the two packages systematically and only new package versions are published to pypi upon a new git tag starting with a "v", e.g. `v1.0.0` for marion and `v0.1.2-howard` for howard.
> This convention will be documented later in the developer guide.

👷(circleci) package howard module

---

.circleci/config.yml
src/howard/howard/issuers/__init__.py
src/howard/howard/issuers/realisation.py
src/howard/howard/templates/marion/certificates/realisation.html
src/howard/howard/tests/issuers/test_realisation.py
src/marion/.pylintrc
src/marion/marion/certificates/issuers/base.py
src/marion/marion/certificates/issuers/dummy.py
src/marion/marion/certificates/migrations/0002_auto_20200910_1453.py
src/marion/marion/certificates/models.py
src/marion/marion/certificates/serializers.py
src/marion/marion/certificates/tests/issuers/test_base.py
src/marion/marion/certificates/tests/test_models.py
src/marion/marion/certificates/tests/test_serializers.py
src/marion/marion/certificates/tests/test_views.py
src/marion/setup.cfg

[pydantic](https://pydantic-docs.helpmanual.io/) seems to be a better solution for `marion`'s schema validation.
It is a more pythonic architecture to manipulate context data. For example, date can be manipulated as `datetime` python object and not as string anymore.
All the JSON schema definitions have been replaced by pydantic models in issuers.

➕(core) replace json schema validation with pydantic model

---

src/marion/setup.cfg

Marion is now distributed as a Django application. Dependencies have to be unpinned to correctly use Marion as an application.
`arrow`, `djangorestframework`, `pydantic` and `Weasyprint` packages have been unpinned

🔧(packages) improve dependencies management

---

CHANGELOG.md
src/howard/CHANGELOG.md
src/howard/howard/__init__.py
src/howard/setup.cfg
src/marion/setup.cfg

- Add `DocumentRequest` model, serializer and API viewset
- Add `DummyDocument` example document issuer
- Implement document issuer pattern
- Draft realisation certificate issuer

Release Marion & Howard 0.1.0

---

src/howard/setup.cfg
src/marion/setup.cfg

Even not referenced on pypi, marion seems to be a reserved project name.
Let's switch to a django-prefixed pattern for project packages.

📦(project) update python package names

---

.circleci/config.yml
CHANGELOG.md
src/howard/CHANGELOG.md
src/howard/howard/__init__.py
src/howard/setup.cfg
src/marion/marion/__init__.py
src/marion/setup.cfg

We've recently renammed Marion & Howard packages as `marion` was a reserved name. Trying to import `marion` or `howard` in a standard installation fails as the `marion` package is not installed.
See detailled description of the issue in #27

Fix package version metadata fetching

---

mkdocs.yml

mk-docs based documentation proposes a color customization. By default, the primary color of the documentation is set to `indigo`.

📝(project) change documentation primary color

---

docs/issuer.md

Double underscores are rendered as bold in markdown. For an URL this is unfortunate.

✏️(project) fix issuer documentation typos

---

docs/contribute.md
docs/issuer.md

`pytest` should be written within an inline code zone in documentation content.

✏️(project) fix pytest typos

---

CHANGELOG.md
src/howard/setup.cfg
src/marion/setup.cfg

- Add Django 3.2 compatibility
- Distribute a complete documentation
- Add package description (README)

Release Marion & Howard 0.2.0

---

CHANGELOG.md
src/howard/CHANGELOG.md
src/howard/setup.cfg
src/marion/setup.cfg

- the `DocumentRequest` model now has a `get_document_path` helper
- Avoid caching pydantic model instance in the `PydanticModelField` to avoid multiple models collisions
- Add certificate issuer
- Rename and resize FUN logo
- Add invoice issuer
- Add package description (README)

Release Marion 0.3.0 & Howard 0.2.0

---

src/howard/CHANGELOG.md
src/howard/setup.cfg

- Fix translation typo in the `certificate` document

Release Howard 0.2.2

---

src/howard/CHANGELOG.md
src/howard/setup.cfg

- Fix path to compile translations after move local files

Release Howard 0.2.3

---

src/howard/CHANGELOG.md
src/howard/setup.cfg

- Useless course description on certificate template

🔖(patch) bump howard release to 0.2.4

---

CHANGELOG.md
src/marion/setup.cfg

- `Weasyprint` 53.0+ is now needed

🔖(patch) bump marion release to 0.3.1

---

renovate.json

In the renovate configuration, when activated, the flag `commitBodyTable` enables to append a table with all the updates in the
commit. 
To fit to our previous commit description with `pybot`, we have activated this flag.

Update Renovate bot configuration

---

src/howard/CHANGELOG.md
src/howard/howard/issuers/certificate.py
src/howard/howard/templates/howard/certificate.html
src/howard/howard/templatetags/howard_tags.py
src/howard/howard/tests/issuers/test_certificate.py
src/howard/howard/tests/templatetags/test_howard_tags.py

1. In the case when a certificate is generated but not persisted, we should be able to provide the `creation_date` through the context query. CertificateIssuer context query should accept a `creation_date` property. This value should be optional and if it is not provided the `created` class property is used.
2. we should be able to pass a base 64 encoded image through context query. So signature and logo field validators should now accepts string  instead of path.

✨(howard) add optional field `creation_date` to certificate issuer

---

src/howard/CHANGELOG.md
src/howard/setup.cfg

- Update CertificateIssuer to add an optional `creation_date` field
into context_query

🔖(patch) bump howard to version 0.2.6

---

CHANGELOG.md
sandbox/settings.py
src/marion/marion/tests/test_utils.py
src/marion/marion/utils.py

`marion.utils.static_file_fetcher` method used previously the built-in method `open` to open static files. But it could lead to some issue when the configured static file storage generates extra static files (e.g: containing hash for cache purpose). In this case, the current logic was not able to find the related static file, but using the `open` method of the StaticFileStorage class allows us to find those files.

🐛(marion) use static storage class to open static files

---

CHANGELOG.md
src/marion/setup.cfg

- Add Django 4.0 compatibility
- Use static storage class to open static files

🔖(marion) bump to version 0.4.0

---

src/howard/CHANGELOG.md
src/howard/setup.cfg

- Enforce to use at least django-marion 0.4.0

Howard - Upgrade marion to 0.4.0 then bump howard to version 0.3.0

---

LICENSE.md
mkdocs.yml

The GIP FUN-MOOC has been renamed France Université Numérique since a few years.
Replace each occurence of GIP FUN-MOOC with France Université Numérique

📝(project) update copyright holder

---

.circleci/config.yml

`buildpack-deps` images are now deprecated. Following CircleCI
recommendation, we've switched them to base convenience images.
References:
[1] https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
[2] https://circleci.com/developer/images/image/cimg/base
gitlint-ignore: all
- Use cimg images
- Add login to Dockerhub step

Update deprecated convenience images

---

CHANGELOG.md
src/howard/CHANGELOG.md
src/howard/setup.cfg
src/marion/setup.cfg

Bump Marion to version 0.5.0
- Add Django 4.2 compatibility
- Add `pdf_options` argument to `AbstractDocument.create` method
Bump Howard to version 0.5.0
- Enforce to use at least django-marion 0.5.0

🔖(all) bump marion & howard to version 0.5.0

---

src/howard/CHANGELOG.md
src/howard/setup.cfg

Changed:
- Enforce to use at least `django-marion` 0.6.0

🔖(minor) bump howard to 0.6.0

---

CHANGELOG.md
renovate.json
src/howard/CHANGELOG.md
src/howard/setup.cfg
src/marion/setup.cfg

- Upgrade `Python` to 3.10
- Upgrade `django-marion` dependency to 0.7.0

Bump marion & howard to 0.7.0

---

CHANGELOG.md
Dockerfile
src/marion/setup.cfg

I noticed that footers/headers did not work in Marion. 
I found out that the latest versions of WeasyPrint do not use Cairo anymore.
If we follow the installation guide in their documentation, it also doesn't work because they forgot to mention `pango1.0-tools` as a dependency.
With this pull request, you will be able to use all the css rules of WeasyPrint like for example declaring the page number at the top of
each page with a css rule like:
```css
@page {
@top-right{
content: "Page " counter(page) " of " counter(pages);
}
}
```

Fix dependencies
